# Generated by Django 4.2.4 on 2023-09-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo_medico', '0002_equipomedico_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipomedico',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='equipomedico',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
