# Generated by Django 4.2.4 on 2023-09-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0001_initial'),
        ('equipo_medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('equipo_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_medico.equipomedico')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
            ],
        ),
    ]
