# Generated by Django 4.2.4 on 2023-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_equipo', models.CharField(choices=[('Standard', 'Standard'), ('ECG', 'ECG'), ('Desfibrilador', 'Desfibrilador'), ('Luz', 'Luz'), ('Esterilizador', 'Esterilizador'), ('Ventilador', 'Ventilador')], default='Standard', max_length=20)),
            ],
        ),
    ]
