# Generated by Django 4.2.4 on 2023-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
        ('equipo_medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomedico',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sede.sede'),
        ),
    ]
